version: 2
jobs:
  github_pull:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project/*.cpp
            - project/*.hpp
            - project/Makefile
            - project/Tests
            - project/Doxygen/Doxyfile

  build_binary:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: make
      - persist_to_workspace:
          root: ~/
          paths:
            - project/terminal
      - store_artifacts:
          path: ~/project/terminal
          destination: Binary file

  cd_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: './terminal < Tests/cd\ test/test.txt > Tests/cd\ test/out.txt'
      - run: 'diff Tests/cd\ test/out.txt Tests/cd\ test/result.txt'
      
  echo_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: './terminal < Tests/echo\ test/test.txt > Tests/echo\ test/out.txt'
      - run: 'diff Tests/echo\ test/out.txt Tests/echo\ test/result.txt'

  ls_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: './terminal < Tests/ls\ test/test.txt > Tests/ls\ test/out.txt'
      - run: 'diff Tests/ls\ test/out.txt Tests/ls\ test/result.txt'

  mkdir_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: './terminal < Tests/mkdir\ test/test.txt > Tests/mkdir\ test/out.txt'
      - run: 'diff Tests/mkdir\ test/out.txt Tests/mkdir\ test/result.txt'

  rm_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: './terminal < Tests/rm\ test/test.txt > Tests/rm\ test/out.txt'
      - run: 'diff Tests/rm\ test/out.txt Tests/rm\ test/result.txt'

  touch_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project
      - run: './terminal < Tests/touch\ test/test.txt > Tests/touch\ test/out.txt'
      - run: 'diff Tests/touch\ test/out.txt Tests/touch\ test/result.txt'

  Doxygen_build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run: 'sudo apt-get install doxygen'
      - run: 'sudo apt-get install graphviz'
      - run: 'doxygen ~/project/Doxygen/Doxyfile'
      - persist_to_workspace:
          root: ~/project/Doxygen/HTML
          path: 
            - html
  
  Doxygen_deploy:
    docker:
      - image: node:8.10.0
    steps:
      - attach_workspace:
          at: project/Doxygen/HTML
      - run: | 
          npm install -g --silent gh-pages@2.0.1
          git config user.email "gaborka812@gmail.com"
          git config user.name "gaborka98"
      - add_ssh_keys:
          fingerprints:
            - "6f:7e:f9:83:73:2c:56:e4:f8:09:a5:55:7f:72:a4:10"
      - run: gh-pages --dotfiles --messages "[skip ci] updates" --dist project/Doxygen/HTML/html

workflows:
  version: 2
  Basics:
    jobs:
      - github_pull
      - build_binary:
          requires:
            - github_pull
      - cd_test:
          requires:
            - mkdir_test
      - echo_test:
          requires:
            - touch_test
      - ls_test:
          requires:
            - mkdir_test
            - touch_test
      - mkdir_test:
          requires:
            - build_binary
      - rm_test:
          requires:
            - mkdir_test
            - touch_test
      - touch_test:
          requires:
            - build_binary
      - Doxygen_build:
          requires:
            - cd_test
            - echo_test
            - ls_test
            - mkdir_test
            - rm_test
            - touch_test
      - Doxygen_deploy:
          requires:
            - Doxygen_build
          filters:
            branches:
              only: master
          
