version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: ~/project
          paths:
            - terminal
            - Tests/*
      - store_artifacts:
          path: terminal
          destination: Binary file
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/project
      - run: './terminal < Tests/test.txt > Tests/out.txt'
      - run: 'diff Tests/out.txt Tests/testresult.txt'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
