version: 2
jobs:
  kiir:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: cat main.cpp
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: g++ *.cpp
workflows:
  version: 2
  build_and_test:
    jobs:
      - kiir
      - build
